### ISSUE TITLE
Can we add schema and prefix/suffix options in the getTable function? 

### ISSUE THREAD

**Issue by hakaitech** [JCoupalK/go-pgdump#1]
I was looking through this and though maybe we could add schema and suffix/prefix options for a little more flexibility? we fetch the tables with matching options, ignore if not set and THOSE tables go to the Dump function allowing a little more comfort.

i would love to open a PR if you'd review

**Comment by JCoupalK** [comment]
Hi,

I just saw your closed PR.

If you would re-open it I would like to merge it after testing it.

**Comment by hakaitech** [comment]
Simple changes, added a struct for schema and suffix,prefix
added query modifications for the same and appended 'schema.table_name' instead of table_name if schema isn't public.

**Comment by JCoupalK** [comment]
Hi,

Just merged it.

I tested it, it made sense and worked as expected.

Thank you
