### ISSUE TITLE
Transaction or table locking?

### ISSUE THREAD

**Issue by Skarlso** [JCoupalK/go-pgdump#10]
The tool doesn't appear to be using any transaction or table locking like pg_dump.

Is that a feature still in development or is the tool intended to be used with other types of locking?

**Comment by JCoupalK** [comment]
Hi,

That is still in development with a bunch of other features (was planning it for the next major version actually whenever I would get to it).

It's not a full pg_dump replacement just yet, a lot more work has to be done but it's coming.

Thank you.

**Comment by Skarlso** [comment]
Thank you for your response! 😊
