### ISSUE TITLE
Dump does not contain actual data

### ISSUE THREAD

**Issue by Skarlso** [JCoupalK/go-pgdump#12]
hello. :D 

Please forgive me if I misunderstand something but I wanted to dump a database of mine and I noticed that it didn't contain any of the actual data but something like this:

```sql
COPY histories (id, created_at, updated_at, deleted_at, status) FROM stdin;
\.
```

I know that the histories database was not empty by the time I ran the script so I'm not sure what to do in this situation. Can you help debug it please? :) Cheers!

**Comment by JCoupalK** [comment]
Hi,

Can you show me your dumper code?

I'll also investigate if something is wrong.

**Comment by Skarlso** [comment]
Hello. :)

This is all I'm doing, maybe the table options isn't supposed to be left empty? :D 

```go
func (d *DefaultStore) Dump(name string, filename string) error {
	// Create a new dumper instance with connection string and number of threads
	connectionDetails := d.DefaultConnectionDetails()
	connection := fmt.Sprintf("host=%s user=%s password=%s dbname=%s port=%d sslmode=disable TimeZone=Etc/UTC", connectionDetails.Host, connectionDetails.User, connectionDetails.Password, name, connectionDetails.Port)
	dumper := pgdump.NewDumper(connection, 50)
	return dumper.DumpDatabase(filename, &pgdump.TableOptions{})
}
```

**Comment by Skarlso** [comment]
Basically, I would like to dump everything... Maybe I need to give the Prefix as `*` then or something?

**Comment by Skarlso** [comment]
Another interesting one is that after the thing is finished, I'm trying to delete the database and I get an error that it's still being used.

Some kind of left over connection that isn't closed perhaps? 

```
db error: ERROR: database \"test-name\" is being accessed by other users (SQLSTATE 55006)"}
```

**Comment by JCoupalK** [comment]
Actually having it empty should be working, it's intended to work that way but I see that it's not for you. With my test database I can't seem to replicate your problem, can you give me an example of your data structure similar to yours?

Also for the left over connection I'll look into it, thank you

**Comment by Skarlso** [comment]
I might be an idiot. I think these tables might actually be empty. 🤣 but I'll verify later today. 

The connection issue is a real one though. 

I'll try to replicate with a sample db too.

**Comment by Skarlso** [comment]
It's actually wooorking 🎉 

```
COPY agents (id, created_at, updated_at, deleted_at, name, enabled, current_status, service_account_key, service_account_name, manifest, tags) FROM stdin;
1                               test
2                               test2
3                               test3
\.
```

So now the connection thing is the only question.

**Comment by Skarlso** [comment]
Actually... the connection open issue might be on my side too. :( 

We are using gorm and that uses connection pooling and that prevents the drop database not the dump...

Reaally sorry for wasting your time on this one. :(

**Comment by JCoupalK** [comment]
No worry glad everything is working for you
