### ISSUE TITLE
Latest tag `0.2` is semantically older than the last tags

### ISSUE THREAD

**Issue by Skarlso** [JCoupalK/go-pgdump#9]
Hello. It looks like the latest tag is actually 0.2 instead of 2.0?

**Comment by Skarlso** [comment]
Oh, it's used as a dump version?
```
const headerTemplate = `-- Go PostgreSQL Dump {{ .DumpVersion }}
```

**Comment by JCoupalK** [comment]
Hi, 

Yes it's used as the dump version but I'm not sure what you mean by 2.0 because it hasn't reached 1.0 yet it was 0.1.1 before.

**Comment by Skarlso** [comment]
Yeh it was only weird because when go was trying to fetch it it didn't actually fetch the latest version.

Can we have something like an environment property instead of calling out to GitHub to determine the dump version please?🙏

**Comment by JCoupalK** [comment]
Yeah I can look into that for the next version

**Comment by Skarlso** [comment]
Thank you! That would be rad. :))

**Comment by JCoupalK** [comment]
Hi, that should be fixed now.
